### ISSUE TITLE
Nefunkční pod Kodi 18

### ISSUE THREAD

**Issue by ToKroCZ** [alladdin/plugin.video.primaplay#23]
Doplněk podle všeho bohužel nefunguje na Kodi 18, [nefunkčnost hlášena](https://www.xbmc-kodi.cz/prispevek-prima-play?page=4) na Androidu i Windows.
@RomanSmolka

**Comment by nizo11** [comment]
Žial dnes v popoludňajších hodinách sa tento problém vyskytol aj na verzii 17.6 Krypton na platforme Amlogic S95x LibreElec v. 8.2-8.2.2.3. Okolo 15. hod. bolo ešte všetko v poriadku.

**Comment by davepee** [comment]
CoreELEC (official): 8.99.2 (S912.arm) - zobrazí se pouze seznam pořadů, složky jednotlivých epizod jsou ale prázdné.

**Comment by Kisuke-CZE** [comment]
Popravde, ted nevim jestli to souvisi s verzi Kodi nebo spis prima zmenila neco na svem webu.

Kazdopadne asi mesic zpet sem updatoval na kodi 18.3. A ted sem zjistil ze plugin nefunguje. V logu kodi se pise:
`2019-07-31 17:38:38.635 T:139972111324928  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.11.07
2019-07-31 17:38:38.740 T:139972111324928   ERROR: [iPrima] ['Traceback (most recent call last):\n', '  File "/opt/Kodi18/.kodi/addons/plugin.video.primaplay/default.py", line 252, in <module>\n    show_navigation(linkurl)\n', '  File "/opt/Kodi18/.kodi/addons/plugin.video.primaplay/default.py", line 78, in show_navigation\n    page = _play_parser.get_show_navigation(pageurl)\n', '  File "/opt/Kodi18/.kodi/addons/plugin.video.primaplay/libPrimaPlay/PrimaPlay.py", line 218, in get_show_navigation\n    content = self.ua.get(link)\n', '  File "/opt/Kodi18/.kodi/addons/plugin.video.primaplay/libPrimaPlay/PrimaPlay.py", line 54, in get\n    res = self.opener.open(req)\n', '  File "/usr/lib/python2.7/urllib2.py", line 435, in open\n    response = meth(req, response)\n', '  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response\n    \'http\', request, response, code, msg, hdrs)\n', '  File "/usr/lib/python2.7/urllib2.py", line 473, in error\n    return self._call_chain(*args)\n', '  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain\n    result = func(*args)\n', '  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default\n    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)\n', 'HTTPError: HTTP Error 404: Not Found\n']
2019-07-31 17:38:38.902 T:139971222558464   ERROR: GetDirectory - Error getting plugin://plugin.video.primaplay/?action=SHOW-NAV&linkurl=%2f%2fcool.iprima.cz%2fporady%2fautosalon
2019-07-31 17:38:38.911 T:139972830283904   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.primaplay/?action=SHOW-NAV&linkurl=%2f%2fcool.iprima.cz%2fporady%2fautosalon) failed`
