### ISSUE TITLE
local variable 'thumbnail' referenced before assignment

### ISSUE THREAD

**Issue by kulheim** [alladdin/plugin.video.primaplay#29]
Kodi 18.04 mi aktuálně nejede:
`2019-09-07 14:26:28.772 T:7670   ERROR: [iPrima] ['Traceback (most recent call last):\n', '  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.primaplay/default.py", line 261, in <module>\n    shows_menu("https://prima.iprima.cz/iprima-api/ListWithFilter/Series/Content?ts="+ str(ts) +"&filter=all&featured_queue_name=iprima:hp-featured-series")\n', '  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.primaplay/default.py", line 73, in shows_menu\n    if video_list.title: add_show(video_list)\n', '  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.primaplay/default.py", line 148, in add_show\n    li = list_item(video_list.title, thumbnail)\n', "UnboundLocalError: local variable 'thumbnail' referenced before assignment\n"]
`

Prozatim mi pomohla tato úprava default.py
```
    def add_show(video_list):
        url = '#'
        if video_list.link:
            url = get_menu_link( action = 'SHOW-NAV', linkurl = video_list.link )
        # if video_list.thumbnail:
        thumbnail = video_list.thumbnail
        li = list_item(video_list.title, thumbnail)
        xbmcplugin.addDirectoryItem(handle=_handle_, url=url, listitem=li, isFolder=True)
```

**Comment by Morfeus70** [comment]
mám stejný problém, půjde to prosím vyřešit ?

**Comment by RMichal66** [comment]
Upravit  `default.py`  tak jak píšu v mém [příspěvku](https://github.com/alladdin/plugin.video.primaplay/issues/30).
